# Generated by Django 4.1 on 2022-09-11 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakshe_cholo_app', '0002_user_coordinates_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coordinates',
            name='designation',
        ),
        migrations.AddField(
            model_name='user_coordinates',
            name='designation',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
