# Generated by Django 4.1 on 2022-09-11 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakshe_cholo_app', '0003_remove_user_coordinates_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coordinates',
            name='designation',
        ),
        migrations.AddField(
            model_name='user_coordinates',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
