# Generated by Django 4.1 on 2022-09-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakshe_cholo_app', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='association',
            new_name='user',
        ),
    ]
